### ISSUE TITLE
wrong? comment

### ISSUE THREAD

**Issue by astraw** [dwrensha/gj#10]
Hi, I was reading the comments for EventLoop._run() ([here](https://github.com/dwrensha/gj/blob/d5cf64b0d8d620c01c675c619c153d88b779c705/src/lib.rs#L406-407)) and they seem to be out of sync with the implementation.

```
This never calls the `EventPort`'s `sleep()` or `poll()`. It will
call the `EventPort`'s `set_runnable(false)` if the queue becomes empty.
```

Unless I'm mistaken somehow, there is no sleep() or poll() for EventPort nor does EventPort have set_runnable().

**Comment by dwrensha** [comment]
Thanks. gj started out as a more-or-less literal port of [kj](https://capnproto.org/cxxrpc.html#kj-concurrency-framework), and this is one of the vestiges. [Removed](https://github.com/dwrensha/gj/commit/f4c4141e3436f2d9d7d40191ee07e5423d479bf0).
