### ISSUE TITLE
Never deregister?

### ISSUE THREAD

**Issue by lcy03406** [dwrensha/gj#3]
Donno if it's the place to discuss such things. Sorry in advance.

Maybe I'm wrong, but I find that the events never deregister from mio. Is that ok?

**Comment by dwrensha** [comment]
Thanks for asking! `epoll()` automatically removes descriptors that have been closed, and I think that `kevent()` acts roughly the same. However, I had not realized until just now that there could be a problem if a file descriptor is `dup()`ed, as can happen through the `try_clone()` call. ( see Q6 in http://man7.org/linux/man-pages/man7/epoll.7.html ) I may need to deregister, after all!

**Comment by dwrensha** [comment]
Fixed in https://github.com/dwrensha/gj/commit/80b5d2718468504de8d4f755d6633c9170c55e8d.
