### ISSUE TITLE
Promise and PromiseFulfiller as their own crate

### ISSUE THREAD

**Issue by bfrog** [dwrensha/gj#9]
I'm finding a usage of Promise and PromiseFulfiller outside of using the gj EventLoop itself and it would be a bonus if I could depend on a Promise only crate for that.

**Comment by dwrensha** [comment]
Could you give an example of what kind of usage you have in mind? 

`Promise` is rather tightly coupled with `EventLoop`, to an extent that I'm doubtful splitting them into separate crates is possible.

Note that it's important that any new computation triggered by `PromiseFulfiller::fulfill()` does not get scheduled until the next turn of the event loop. So, for example, the following program prints "hello" before "world":

```rust
    EventLoop::top_level(|wait_scope| -> Result<(), ()> {
        let (p, f) = Promise::and_fulfiller();
        let p = p.then(|()| {
            println!("world");
            Promise::ok(())
        });

        f.fulfill(());
        println!("hello");
        p.wait(wait_scope, &mut ClosedEventPort(()))
    }).unwrap();

```

**Comment by bfrog** [comment]
I realize now that its too tightly coupled with the eventloop to make it useful outside of here.

I guess I was thinking of it being useful for something akin to a one shot Result<T, E> channel but clearly that won't work the way I was thinking
